/* Generated By:JavaCC: Do not edit this line. PCodeParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PCodeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int STRING = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"print\"",
    "\"add\"",
    "\"sub\"",
    "\"mul\"",
    "\"div\"",
    "\"dup\"",
    "\"load\"",
    "\"store\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 13>",
    "<VARIABLE>",
    "<EXPONENT>",
    "<NUMBER>",
    "<STRING>",
  };

}
